#!/usr/bin/python
#coding:utf-8

docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'

kubectl create clusterrolebinding system:anonymous --clusterrole=cluster-admin --user=system:anonymous


import RPi.GPIO as GPIO
import time

channel =4
def test():
    data = []
    j = 0

    GPIO.setmode(GPIO.BCM)

    time.sleep(1)

    GPIO.setup(channel, GPIO.OUT)
    GPIO.output(channel, GPIO.LOW)
    time.sleep(0.02)
    GPIO.output(channel, GPIO.HIGH)
    GPIO.setup(channel, GPIO.IN)

    while GPIO.input(channel) == GPIO.LOW:
      continue
    while GPIO.input(channel) == GPIO.HIGH:
      continue

    while j < 40:
      k = 0
      while GPIO.input(channel) == GPIO.LOW:
        continue
      while GPIO.input(channel) == GPIO.HIGH:
        k += 1
        if k > 100:
          break
      if k < 8:
        data.append(0)
      else:
        data.append(1)

      j += 1

    print "sensor is working."
    print data

    humidity_bit = data[0:8]
    humidity_point_bit = data[8:16]
    temperature_bit = data[16:24]
    temperature_point_bit = data[24:32]
    check_bit = data[32:40]

    humidity = 0
    humidity_point = 0
    temperature = 0
    temperature_point = 0
    check = 0

    for i in range(8):
      humidity += humidity_bit[i] * 2 ** (7-i)
      humidity_point += humidity_point_bit[i] * 2 ** (7-i)
      temperature += temperature_bit[i] * 2 ** (7-i)
      temperature_point += temperature_point_bit[i] * 2 ** (7-i)
      check += check_bit[i] * 2 ** (7-i)

    tmp = humidity + humidity_point + temperature + temperature_point

    if check == tmp:
      print "temperature :", temperature, "*C, humidity :", humidity, "%"
    else:
      print "wrong"
      print "temperature :", temperature, "*C, humidity :", humidity, "% check :", check, ", tmp :", tmp

#主程序
try:
    while True:
        test()

GPIO.cleanup()

import RPi.GPIO as GPIO
import time

channel =4
data = []
j = 0

GPIO.setmode(GPIO.BCM)

time.sleep(1)

GPIO.setup(channel, GPIO.OUT)
GPIO.output(channel, GPIO.LOW)
time.sleep(0.02)
GPIO.output(channel, GPIO.HIGH)
GPIO.setup(channel, GPIO.IN)

while GPIO.input(channel) == GPIO.LOW:
  continue
while GPIO.input(channel) == GPIO.HIGH:
  continue

while j < 40:
  k = 0
  while GPIO.input(channel) == GPIO.LOW:
    continue
  while GPIO.input(channel) == GPIO.HIGH:
    k += 1
    if k > 100:
      break
  if k < 8:
    data.append(0)
  else:
    data.append(1)

  j += 1

print "sensor is working."
print data

humidity_bit = data[0:8]
humidity_point_bit = data[8:16]
temperature_bit = data[16:24]
temperature_point_bit = data[24:32]
check_bit = data[32:40]

humidity = 0
humidity_point = 0
temperature = 0
temperature_point = 0
check = 0

for i in range(8):
  humidity += humidity_bit[i] * 2 ** (7-i)
  humidity_point += humidity_point_bit[i] * 2 ** (7-i)
  temperature += temperature_bit[i] * 2 ** (7-i)
  temperature_point += temperature_point_bit[i] * 2 ** (7-i)
  check += check_bit[i] * 2 ** (7-i)

tmp = humidity + humidity_point + temperature + temperature_point

if check == tmp:
  print "temperature :", temperature, "*C, humidity :", humidity, "%"
else:
  print "wrong"
  print "temperature :", temperature, "*C, humidity :", humidity, "% check :", check, ", tmp :", tmp

GPIO.cleanup()


import RPi.GPIO as GPIO
import time

GREEN = 26
YELLOW = 19
RED = 13

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(GREEN, GPIO.OUT)    #设置bcm26负责输出电压 红灯
GPIO.setup(YELLOW,GPIO.OUT)     #黄灯
GPIO.setup(RED,GPIO.OUT)     #绿灯

#主程序
try:
    #循环执行
    while True:
      t=1
      if t==1:
          GPIO.output(RED,False)
          GPIO.output(YELLOW,False)
          GPIO.output(GREEN,True)
          time.sleep(2)
          t=2
      t==2:
          GPIO.output(RED,True)
          GPIO.output(YELLOW,False)
          GPIO.output(GREEN,False)
          time.sleep(2)
          t=3
      t==3:
          GPIO.output(RED,False)
          GPIO.output(YELLOW,True)
          GPIO.output(GREEN,False)
          time.sleep(2)
          t=1

except KeyboardInterrupt:
    pass

GPIO.cleanup()


https://bbs.huaweicloud.com/forum/thread-13022-1-1.html

https://cloud.tencent.com/developer/article/1039556

http://www.ruiwen.com/zuowen/sucai/87095.html
{
  "dnsEndpoint": "https://dns.myhuaweicloud.com/v2",
  "projectId":"",
  "region": "cn-north-1",
  "accessKey": "",
  "secretKey": "",
  "serviceType": "all",
}
{
  "iamEndpoint": "https://iam.myhuaweicloud.com/v3/auth/tokens/",
  "dnsEndpoint": "https://dns.myhuaweicloud.com/v2",
  "projectId":"",
  "username": "",
  "password": "",
  "domainname":"",
  "region": "cn-north-1",
  "accessKey": "",
  "secretKey": "",
  "serviceType": "all",
}


multiclusterdns.federation.k8s.io/v1alpha1
https://www.youtube.com/watch?v=9HQ2XgL9YVI

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: external-dns:v1
        args:
        - --source=service
        - --source=ingress
        - --provider=huawei
        volumeMounts:
        - name: huawei-config
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: huawei-config
        secret:
          secretName: huawei-config
	  
	 
{
  "iamEndpoint": "https://iam.myhuaweicloud.com/v3/auth/tokens",
  "dnsEndpoint": "https://dns.myhuaweicloud.com/v2",
  "projectId":"",
  "username": "",
  "password": "",
  "domainname":"",
}

https://iam.cn-north-1.myhuaweicloud.com/v3/auth/tokens

https://www.ibm.com/developerworks/cn/linux/kernel/l-thread/index.html
https://blog.lab99.org/post/golang-2017-10-04-video-understanding-channels.html

https://play.golang.org/p/lSmQahlGtJm
https://www.ibm.com/developerworks/cn/linux/l-lvm2/
https://github.com/kubernetes/kubernetes/issues/61433
http://licyhust.com/%E5%AE%B9%E5%99%A8%E6%8A%80%E6%9C%AF/2016/09/07/k8s-watch-client-1/
https://docs.google.com/document/d/1fj3yzmeU2eU8ZNBCUJG97dk_wC7228-e_MmdcmTNrZY/edit?ts=5a723935#heading=h.8ngolbigvi7q
fisherxu1@gmail.com
1and1internet/ubuntu-16-nginx
docker pull mirrorgooglecontainers/kube-apiserver-amd64:v1.7.5
https://hub.docker.com/r/mirrorgooglecontainers/kube-apiserver-amd64/tags/
docker pull mirrorgooglecontainers/k8s-dns-dnsmasq-nanny-amd64:1.14.4
gen-swagger-docs:v8
docker pull googlecontainer/gen-swagger-docs
Source Synchronizer
Remote Hosts Access
http://licyhust.com/%E5%AE%B9%E5%99%A8%E6%8A%80%E6%9C%AF/2016/10/06/k8s-api/
https://free.aliyun.com/ntms/free/experience/getTrial.html?spm=5176.7973419.726407.45.7b330314Y0Lqnh
http://www.10tiao.com/html/557/201509/214548448/2.html
chakri-nelluri
https://jicki.me/2017/07/04/kubernetes-1.7.0/
http://ma0921.manlf.cn/app/index.php?jump=1&c=entry&do=show&m=xiaof_toupiao&i=5&sid=14&id=266&wxref=mp.weixin.qq.com&from=timeline&isappinstalled=0

make -j 8 WHAT=test/e2e/e2e.test
_output/bin/e2e.test --host="http://127.0.0.1:8080" --provider="local" --ginkgo.v=true --kubeconfig="$HOME/.kube/config" --repo-root="$GOPATH/src/k8s.io/kubernetes" \--ginkgo.focus="should create and stop a working application"
update-generated-protobuf.sh
http://hant.ask.helplib.com/git/post_19698

docker login -u cn-north-1@2paLAtfxW4PIVMHJU8Gv -p 2592d613aa90af01a973954ec3cbd23a27742c13cefd08e1e81b9ccbe080ff0c swr.cn-north-1.myhuaweicloud.com


https://github.com/kubernetes/kubernetes/pull/50146

package main

import (
	"fmt"

	"net"
	"net/http"
	_ "os"
	_ "reflect"
)

type Foo struct {
	X string `json:"x,omitempty"`
	Y *int
}

func (f Foo) Do() *int {
	return f.Y
}

func main() {
	//var i []int = []int{1, 2}
	//i = append(i, 6)
	////var foo Foo
	//var f = &Foo{"", nil}
	//typ := reflect.TypeOf(f)
	////fmt.Println(typ.MethodByName().)
	////fmt.Println(reflect.TypeOf(foo)) //main.Foo
	//
	//fmt.Println(typ)
	//
	//var s = "abc"
	//fmt.Println(reflect.ValueOf(i)) //<int Value>
	//fmt.Println(reflect.ValueOf(f)) //<main.Foo Value>
	//fmt.Println(reflect.ValueOf(s))
	//
	//fmt.Println(os.Hostname())
	//
	//var a interface{} = 1.1
	//v, ok := a.(float64)
	//if !ok {
	//	fmt.Println("failure")
	//	return
	//}
	//fmt.Println("Where are you,Jonny?", v)
	h := http.FileServer(http.Dir("/tmp"))
	l, _ := net.Listen("tcp", getLocalIp()+":0")
	fmt.Println(l.Addr().String())
	err := http.Serve(l, h)
	if err != nil {
		fmt.Println("err", err)
	}
}

type Ts struct {
	URL string
}

func getLocalIp() string {
	var IpAddr string
	ifaces, _ := net.Interfaces()
	for _, iface := range ifaces {
		if iface.Name == "eth0" {
			addrs, _ := iface.Addrs()
			for _, addr := range addrs {
				if ipnet, ok := addr.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
					if nil != ipnet.IP.To4() {
						IpAddr = ipnet.IP.String()
						return IpAddr
					}
				}
			}
		}
	}
	return ""
}


type Ts struct {
        URL string
}

func (t Ts) Close() {
        return
}

func getLocalIp() string {
        var IpAddr string
        ifaces, _ := net.Interfaces()
        for _, iface := range ifaces {
                if iface.Name == "eth0" {
                        addrs, _ := iface.Addrs()
                        for _, addr := range addrs {
                                if ipnet, ok := addr.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
                                        if nil != ipnet.IP.To4() {
                                                IpAddr = ipnet.IP.String()
                                                return IpAddr
                                        }
                                }
                        }
                }
        }
        return ""
}

func StartSimpleHttp() Ts {
        h := http.FileServer(http.Dir(strings.Join([]string{TestContext.RepoRoot, "/test/e2e/testing-manifests/process/"}, "")))
        l, _ := net.Listen("tcp", getLocalIp()+":0")
        go http.Serve(l, h)

        ts := Ts{
                URL: l.Addr().String(),
        }
        return ts
}

Nov 13 18:56:47.652: INFO: Failed to get response from guestbook. err: <nil>, response: <br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://:6379]' in /usr/local/lib/php/Predis/Connection/AbstractConnection.php:168
Stack trace:
#0 /usr/local/lib/php/Predis/Connection/StreamConnection.php(97): Predis\Connection\AbstractConnection-&gt;onConnectionError('php_network_get...', 0)
#1 /usr/local/lib/php/Predis/Connection/StreamConnection.php(58): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\Parameters))
#2 /usr/local/lib/php/Predis/Connection/AbstractConnection.php(94): Predis\Connection\StreamConnection-&gt;createResource()
#3 /usr/local/lib/php/Predis/Connection/StreamConnection.php(158): Predis\Connection\AbstractConnection-&gt;connect()
#4 /usr/local/lib/php/Predis/Connection/AbstractConnection.php(193): Predis\Connection\StreamConnection-&gt;connect()
#5 /usr/local/lib/php/Predis/Connection/StreamConnection.php(184): Predis\Connection\AbstractConnection-&gt;getResource()
#6 /us in <b>/usr/local/lib/php/Predis/Connection/AbstractConnection.php</b> on line <b>168</b><br />

Nov 13 18:56:52.677: INFO: Failed to get response from guestbook. err: <nil>, response: <br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://:6379]' in /usr/local/lib/php/Predis/Connection/AbstractConnection.php:168
Stack trace:
#0 /usr/local/lib/php/Predis/Connection/StreamConnection.php(97): Predis\Connection\AbstractConnection-&gt;onConnectionError('php_network_get...', 0)
#1 /usr/local/lib/php/Predis/Connection/StreamConnection.php(58): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\Parameters))
#2 /usr/local/lib/php/Predis/Connection/AbstractConnection.php(94): Predis\Connection\StreamConnection-&gt;createResource()
#3 /usr/local/lib/php/Predis/Connection/StreamConnection.php(158): Predis\Connection\AbstractConnection-&gt;connect()
#4 /usr/local/lib/php/Predis/Connection/AbstractConnection.php(193): Predis\Connection\StreamConnection-&gt;connect()
#5 /usr/local/lib/php/Predis/Connection/StreamConnection.php(184): Predis\Connection\AbstractConnection-&gt;getResource()
#6 /us in <b>/usr/local/lib/php/Predis/Connection/AbstractConnection.php</b> on line <b>168</b><br />

func SetDefaults_ObjectMeta(obj *ObjectMeta) {
	if obj.Enable == nil {
		obj.Enable = new(bool)
		*obj.Enable = true
	}
}


sw.Do("for $.index$ := range $.var$ {\n", vars)
		if len(n.children) > 0 && n.children[0].elem {
			sw.Do("$.local$ := $.var$[$.index$]\n", vars)
		} else {
			sw.Do("$.local$ := &$.var$[$.index$]\n", vars)
		}
		
		vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
		
		if t.Elem.Kind == types.Pointer {
				child.elem = true
			}
			
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/
825992

root@SZX1000353073:~/codes/src/k8s.io/kubernetes# python hack/boilerplate/boilerplate.py -v
File /root/codes/src/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go has the year
/root/codes/src/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go


####
